# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Unstable Archives'
description:      'Gender & Empire in South Asia'
url:              'https://unstable-archives.github.io'
baseurl:          '/unstable_archives'
copyright:        '2021 Megan Eaton Robb'
logo:             '/img/pendant_transparent.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  unstable_archives: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'unstable_archives_item' # the layout for the pages to use
    metadata:
      source: 'unstable_archives.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/ua_directory' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      unstable_archives:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - translation
          - transcription
          - summary
          - contents
          - keywords
          - object_type
          - shelfmark
          - metadata_creators
          - repository_city
          - roles
          - _date
          - place_origin
          - provenance_details
          - language
          - decoration
          - layout
          - hand_script
          - dimensions
          - additional_info
          - notes_digitizer
          - copyright_statement
          - images

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'Introduction'
    sub:
      - label: 'Introduction'
        link: '/introduction/'
      - label: 'Historical Context'
        link: '/historical_context/'
      - label: 'Timeline'
        link: '/timeline/'
      - label: 'Travels'
        link: '/travels/'
      - label: 'Bibliography'
        link: '/bibliography/'
  - label: 'Exhibits'
    sub:
      - label: 'Family'
        link: '/exhibits/family/'
      - label: 'Religion'
        link: '/exhibits/religion/'
      - label: 'Scribal Cultures'
        link: '/exhibits/scribal_cultures/'
      - label: 'Attire'
        link: '/exhibits/attire/'
      - label: 'Law & Land'
        link: '/exhibits/law_land/'
      - label: 'Law & Interracial Marriage'
        link: '/exhibits/law_interracial_marriage/'
      - label: 'Attitudes towards Interracial Romance'
        link: '/attitudes_towards_interracial_romance/'
      - label: 'Ryots and Company Rule'
        link: '/ryots_and_company_rule/'  
  - label: 'Scholarship'
    sub:
      - label: 'DH & Family Archives'
        link: '/dh_family_archives/'
      - label: 'Stakes & Literature'
        link: '/stakes_literature/'
      - label: 'Scholarship'
        link: '/scholarship/'
      - label: 'Silences'
        link: '/silences/'
      - label: 'Our Approach'
        link: '/approach/'
  - label: 'Teaching Resources'
    sub:
      - label: 'Reading Resources'
        link: '/reading_resources_for_teachers/'
      - label: 'Bibliography for Scholars'
        link: '/bibliography_for_scholars/'
  - label: 'Browse'
    sub:
      - label: 'Browse'
        link: '/collection/'
      - label: 'Search'
        link: '/search/'
      - label: 'Reuse'
        link: '/reuse/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'Wax'
      link: '/credits'
    - label: 'Contact'
      link: 'mailto:unstablearchives2020@gmail.com'
  logos:
    - img: '/img/pendant_transparent.png'
    - img: '/img/penn_logo.png'

# FIN
